// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFNerMX5qnVPCLxWe29IsInBoauvSIAkk',
    appId: '1:877260324568:web:3225c188efe408c116e1ad',
    messagingSenderId: '877260324568',
    projectId: 'elegantmedicalcenter-bfba2',
    authDomain: 'elegantmedicalcenter-bfba2.firebaseapp.com',
    storageBucket: 'elegantmedicalcenter-bfba2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAt0F62kxcKZ6q5l2bOAh8ipC6G7BIsCg',
    appId: '1:877260324568:android:a5960836d8c8bda116e1ad',
    messagingSenderId: '877260324568',
    projectId: 'elegantmedicalcenter-bfba2',
    storageBucket: 'elegantmedicalcenter-bfba2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRYBAYdXggXv5OSpQjxRFmv-W8owk-rrY',
    appId: '1:877260324568:ios:246cbde0756ade8716e1ad',
    messagingSenderId: '877260324568',
    projectId: 'elegantmedicalcenter-bfba2',
    storageBucket: 'elegantmedicalcenter-bfba2.firebasestorage.app',
    iosBundleId: 'com.example.emc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRYBAYdXggXv5OSpQjxRFmv-W8owk-rrY',
    appId: '1:877260324568:ios:246cbde0756ade8716e1ad',
    messagingSenderId: '877260324568',
    projectId: 'elegantmedicalcenter-bfba2',
    storageBucket: 'elegantmedicalcenter-bfba2.firebasestorage.app',
    iosBundleId: 'com.example.emc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFNerMX5qnVPCLxWe29IsInBoauvSIAkk',
    appId: '1:877260324568:web:e55859a476dacade16e1ad',
    messagingSenderId: '877260324568',
    projectId: 'elegantmedicalcenter-bfba2',
    authDomain: 'elegantmedicalcenter-bfba2.firebaseapp.com',
    storageBucket: 'elegantmedicalcenter-bfba2.firebasestorage.app',
  );
}
